[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
wusd_application = "3JmdookeJY96JsRnnN1C68qLiKmqrw6LuEhK9yhdKfWJ"
wusd_token = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/*"]
types = "types/"
