[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
wusd_stablecoin = "FzQFfVXCNxFEH9EADpVurFgUZ5WKKtYpYC5okGJHoTzh"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "deploy-keypair.json"

[workspace]
members = ["programs/*"]
types = "types/"
