[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
wusd_stablecoin = "Hqdm6x74og9EjPXSnTYkoXss9JeF3ZkL67Ziq2CMFYZr"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*"]
types = "types/"
