[toolchain]
anchor_version = "0.28.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
wusd_application = "9VBdBHsx836ER2ejyetGvG7MWmpNwRg5Kc9FBfixCzCf"
wusd_token = "9VBdBHsx836ER2ejyetGvG7MWmpNwRg5Kc9FBfixCzCf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
  "programs/wusd-application",
  "programs/wusd-token"
]
types = "types/"

[test.validator]
compute_max_units = 1400000
accounts = []
